Remove integration testing for now

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -101,50 +101,52 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  integration-test:
-    executor: builder
-    steps:
-      - attach_workspace:
-          at: .
-      - run:
-          name: integration tests
-          command: |
-            . .circleci/env.sh
-            cd infrastructure
-            terraform workspace new $DEPLOY_STAGE || terraform workspace select $DEPLOY_STAGE
-            terraform apply --auto-approve -var ssm_source_stage=$SSM_SOURCE_STAGE -var account_id=$ACCOUNT_ID -no-color
-            cd ..
-            set +e # allows us to run the cleanup
-            npx sls --stage=$DEPLOY_STAGE deploy
-            export SUCCESS=$?
-            npx sls --stage=$DEPLOY_STAGE exportEndpoints
-            if [ $? != 0 ]; then
-              export SUCCESS=1
-            fi
-            npx sls --stage=$DEPLOY_STAGE s3deploy
-            if [ $? != 0 ]; then
-              export SUCCESS=1
-            fi
-            pytest --junitxml=test-reports/junit.xml -m integration tests
-            if [ $? != 0 ]; then
-              export SUCCESS=1
-            fi
-            exit $SUCCESS
-      - store_test_results:
-          path: test-reports
-
-  integration-env-tear-down:
-    executor: builder
-    steps:
-      - attach_workspace:
-          at: .
-      - run:
-          name: integration env tear down
-          command: |
-            . .circleci/env.sh
-            npx sls --stage=$DEPLOY_STAGE remove
-      - store_test_results:
-          path: test-reports
+# Deploying the domain for each branch is very expensive, for now omitting integration tests
+# until we have a better plan e.g. re-using the domain.
+#  integration-test:
+#    executor: builder
+#    steps:
+#      - attach_workspace:
+#          at: .
+#      - run:
+#          name: integration tests
+#          command: |
+#            . .circleci/env.sh
+#            cd infrastructure
+#            terraform workspace new $DEPLOY_STAGE || terraform workspace select $DEPLOY_STAGE
+#            terraform apply --auto-approve -var ssm_source_stage=$SSM_SOURCE_STAGE -var account_id=$ACCOUNT_ID -no-color
+#            cd ..
+#            set +e # allows us to run the cleanup
+#            npx sls --stage=$DEPLOY_STAGE deploy
+#            export SUCCESS=$?
+#            npx sls --stage=$DEPLOY_STAGE exportEndpoints
+#            if [ $? != 0 ]; then
+#              export SUCCESS=1
+#            fi
+#            npx sls --stage=$DEPLOY_STAGE s3deploy
+#            if [ $? != 0 ]; then
+#              export SUCCESS=1
+#            fi
+#            pytest --junitxml=test-reports/junit.xml -m integration tests
+#            if [ $? != 0 ]; then
+#              export SUCCESS=1
+#            fi
+#            exit $SUCCESS
+#      - store_test_results:
+#          path: test-reports
+#
+#  integration-env-tear-down:
+#    executor: builder
+#    steps:
+#      - attach_workspace:
+#          at: .
+#      - run:
+#          name: integration env tear down
+#          command: |
+#            . .circleci/env.sh
+#            npx sls --stage=$DEPLOY_STAGE remove
+#      - store_test_results:
+#          path: test-reports
 
   deploy:
     executor: builder
@@ -168,15 +170,17 @@ workflows:
       - setup
       - unit-test:
           requires: [ setup ]
-      - integration-test:
-          requires: [ setup ]
-      - integration-env-tear-down:
-          requires: [ integration-test ]
+# No integration tasks until we work out how to avoid 20 mins of setup and tear down
+#      - integration-test:
+#          requires: [ setup ]
+#      - integration-env-tear-down:
+#          requires: [ integration-test ]
       - approve:
           type: approval
           requires:
             - unit-test
-            - integration-test
+# No integration tasks until we work out how to avoid 20 mins of setup and tear down
+#            - integration-test
           <<: *master-only
       - deploy:
           requires: [ approve ]
